### ISSUE TITLE
Negative numbers not converted to string correctly

### ISSUE THREAD

**Issue by dpbevin** [Backbase/backbase-openapi-tools#5]
I tried running one of the DBS specs (account-presentation-spec) through the converter and found that yaml validation failed on negative numbers in an example. If you look in the arrangements-with-balance-history-ex.json file, there's a section that looks like this:
```
        {
          "dateFrom": "2017-06-12T00:00:00.000Z",
          "dateTo": "2017-07-01T00:00:00.000Z",
          "value": {
            "currency": "EUR",
            "balance": "4"
          },
          "valuePtc": "4"
        },
        {
          "dateFrom": "2017-06-18T00:00:00.000Z",
          "dateTo": "2017-07-01T00:00:00.000Z",
          "value": {
            "currency": "EUR",
            "balance": "-14"
          },
          "valuePtc": "-14"
        }
```

It is the **valuePtc** at the bottom (set to "-14") that gets generated to yaml as this:

```
  - dateFrom: 2017-06-12T00:00:00.000Z
    dateTo: 2017-07-01T00:00:00.000Z
    value:
      currency: EUR
      balance: "4"
    valuePtc: "4"
  - dateFrom: 2017-06-18T00:00:00.000Z
    dateTo: 2017-07-01T00:00:00.000Z
    value:
      currency: EUR
      balance: -14
    valuePtc: -14
```

You can see the difference between between "4" and -14.

I debugged the code and tracked it down to the Jackson YAML library (jackson-dataformat-yaml) that's used to generate the YAML.

The regex that's used to determine the quote rules doesn't handle negative numbers correctly. See https://github.com/FasterXML/jackson-dataformats-text/blob/d69291651114b9e7a2ccbe1a3a154f2b84f95b30/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java#L175

I'm working on a PR for the Jackson library and will link here once submitted.
