### ISSUE TITLE
Bug: List of Maps of Strings generated code does not compile.

### ISSUE THREAD

**Issue by jjjasper** [Backbase/backbase-openapi-tools#647]
Schema type defined as
```
type: object
properties:
  challenges:
    type: array
    items:
      type: object
      additionalProperties:
        type: string
  data:
    type: object
    additionalProperties:
      type: string   
```
Results in 
```
@Valid
private List<Map&lt;String, String&gt;> challenges;
```
